#     _         _                        _   _                 
#    / \  _   _| |_ ___  _ __ ___   __ _| |_(_) ___  _ __  ___ 
#   / _ \| | | | __/ _ \| '_ ` _ \ / _` | __| |/ _ \| '_ \/ __|
#  / ___ \ |_| | || (_) | | | | | | (_| | |_| | (_) | | | \__ \
# /_/   \_\__,_|\__\___/|_| |_| |_|\__,_|\__|_|\___/|_| |_|___/


# Refresh Google Assistant
- alias: "Refresh Google Assistant"
  hide_entity: true
  trigger:
    platform: homeassistant
    event: start
  action:
    service: google_assistant.request_sync
    data:
      agent_user_id: !secret google_agent_id


# Notify me about updates
- alias: "Home Assistant Update"
  initial_state: True
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    service: notify.mobile_app_jesse_s_pixel_3
    data:
      message: "New version {{ states.updater.updater.state }} of Home Assistant is available."


# Delete old Images from Motion
- alias: 'Cleanup Motion Images'
  trigger:
    - platform: time
      at: '1:00:00'
  action:
    service: shell_command.cleanup_motion_images
    
    
- alias: "Turn on Bob's light"
  trigger:
    - platform: time
      at: '7:00:00'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.plant_light
      
    
- alias: "Turn off lights"
  trigger:
    - platform: time
      at: '11:00:00'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.plant_light
    - service: switch.turn_off
      data:
        entity_id: switch.smart_outdoor_plug
        
