#  ____  _                          ____                                
# | __ )(_)_ __   __ _ _ __ _   _  / ___|  ___ _ __  ___  ___  _ __ ___ 
# |  _ \| | '_ \ / _` | '__| | | | \___ \ / _ \ '_ \/ __|/ _ \| '__/ __|
# | |_) | | | | | (_| | |  | |_| |  ___) |  __/ | | \__ \ (_) | |  \__ \
# |____/|_|_| |_|\__,_|_|   \__, | |____/ \___|_| |_|___/\___/|_|  |___/
#                           |___/  

- platform: workday
  country: 'CA'
  province: 'QC'
