#  _   _                  ____             __ _       
# | | | | __ _ ___ ___   / ___|___  _ __  / _(_) __ _ 
# | |_| |/ _` / __/ __| | |   / _ \| '_ \| |_| |/ _` |
# |  _  | (_| \__ \__ \ | |__| (_) | | | |  _| | (_| |
# |_| |_|\__,_|___/___/  \____\___/|_| |_|_| |_|\__, |
#                                                |___/ 

# General config
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: America/Montreal
  customize: !include customize.yaml
  # Include Packages
  packages: !include_dir_named packages
  whitelist_external_dirs:
   - /tmp
   - /share

# Online site
http:
  base_url: !secret external_hass_url 
  use_x_forwarded_for: true
  trusted_proxies: 
    - !secret hass_ip
    - !secret hass_external_ip
    - 127.0.0.1
    - ::1
    - 192.168.0.0/24
    - fd00::/8
   
# Force yaml mode for Lovelace
lovelace:
  mode: yaml

# Google Assistant Integration
google_assistant:
  project_id: home-assistant-6e540
  service_account: !include google-service-account.json
  report_state: true

# Add environment canada
weather:
  - platform: environment_canada
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    forecast: 'hourly'
    name: environment_canada_home

# Enables System Health
system_health:
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
# Enables support for tracking state changes over time.
history:
# Add Configuration Panel
config:
# Enable link to map
map:
# Enable sun tracking
sun:

updater:
  include_used_components: true

# https://fontawesome.com/icons?d=gallery&m=free
# Enable fontawesome icons
fontawesome:
  regular:
  solid:
  brands:

# Car configuration
nissan_leaf:
  username: !secret email 
  password: !secret password
  region: "NCI"
  update_interval:
    hours: 1
  update_interval_charging:
    minutes: 15
  update_interval_climate:
    minutes: 5

# Custom sensors
sensor: !include_dir_merge_list sensors/

# pi hole
pi_hole:
  - host: 'localhost:4865'

# IFTTT Key
ifttt:
  key: !secret ifttt_key

# Text to speech
tts:
  - platform: google_translate

# Account for Meross Cloud
meross_cloud:
  username: !secret email 
  password: !secret old_password 

# Google Credentials
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

# Link to Roomba
vacuum:
  - platform: roomba
    name: Rotom
    host: !secret roomba_ip
    username: !secret roomba_username 
    password: !secret roomba_password

# Web notifications
notify:
  - platform: html5
    name: web
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret email

# Themes
frontend:
  themes: !include_dir_merge_named themes

# Includes
automation: !include automations.yaml
binary_sensor: !include binary-sensors.yaml
cover: !include covers.yaml
device_tracker: !include device-trackers.yaml
garbage_collection: !include garbage-collection.yaml
group: !include groups.yaml
logger: !include logger.yaml
person: !include people.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
switch: !include switches.yaml
zone: !include zones.yaml
