#   ____                        
#  / ___|_____   _____ _ __ ___ 
# | |   / _ \ \ / / _ \ '__/ __|
# | |__| (_) \ V /  __/ |  \__ \
#  \____\___/ \_/ \___|_|  |___/

# Floof's Door sensor
- platform: mqtt
  name: "Floof's Door"
  state_topic: "homeassistant/cover/floofs_door/state"
  state_open: "open"
  state_closed: "closed"
  retain: true
