#  ____             _            _____               _                 
# |  _ \  _____   _(_) ___ ___  |_   _| __ __ _  ___| | _____ _ __ ___ 
# | | | |/ _ \ \ / / |/ __/ _ \   | || '__/ _` |/ __| |/ / _ \ '__/ __|
# | |_| |  __/\ V /| | (_|  __/   | || | | (_| | (__|   <  __/ |  \__ \
# |____/ \___| \_/ |_|\___\___|   |_||_|  \__,_|\___|_|\_\___|_|  |___/

# Network devices
- platform: arpscan_tracker
  interval_seconds: 15
  consider_home: 60
  track_new_devices: true
  scan_options: " --interface=eth0 192.168.2.0/24 -g"
  exclude:
    - !secret hass_ip
