#  _                   _                
# | |    _____   _____| | __ _  ___ ___ 
# | |   / _ \ \ / / _ \ |/ _` |/ __/ _ \
# | |__| (_) \ V /  __/ | (_| | (_|  __/
# |_____\___/ \_/ \___|_|\__,_|\___\___|

title: Maison Mauve
background: var(--background-image)
resources:
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  # https://github.com/thomasloven/lovelace-fold-entity-row
  - url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
    type: module
  # https://github.com/custom-cards/bar-card
  - url: /community_plugin/bar-card/bar-card.js
    type: js
  # https://github.com/ljmerza/calendar-card  
  - url: /community_plugin/calendar-card/calendar-card.js
    type: js
  # https://github.com/kalkih/mini-media-player
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  # https://github.com/amaximus/garbage-collection-card
  - url: /community_plugin/garbage-collection-card/garbage-collection-card.js
    type: module
  # https://github.com/benct/lovelace-xiaomi-vacuum-card
  - url: /community_plugin/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
    type: module
  # https://github.com/custom-cards/vertical-stack-in-card
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  # https://github.com/custom-cards/entity-attributes-card
  - url: /community_plugin/entity-attributes-card/entity-attributes-card.js
    type: module
  # https://github.com/xMrVizzy/button-toolbar
  # - url: /community_plugin/button-toolbar/button-toolbar.js
  #   type: module
  # https://github.com/thomasloven/lovelace-card-mod
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: module
  # https://github.com/thomasloven/lovelace-auto-entities
  - url: /community_plugin/lovelace-auto-entities/auto-entities.js
    type: module
  # https://github.com/custom-cards/bignumber-card
  - url: /community_plugin/bignumber-card/bignumber-card.js
    type: module
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  # https://github.com/Villhellm/lovelace-animated-background
  # - url: /community_plugin/lovelace-animated-background/animated-background.js
  #   type: module

# animated_background:
#   default_url: /community_plugin/lovelace-animated-background/background-animations/sunny.html
#   entity: "weather.dark_sky"
#   state_url:
#       'sunny': /community_plugin/lovelace-animated-background/background-animations/sunny.html
#       'partlycloudy': /community_plugin/lovelace-animated-background/background-animations/cloudy.html
#       'cloudy': /community_plugin/lovelace-animated-background/background-animations/cloudy.html
#       'mostlycloudy': /community_plugin/lovelace-animated-background/background-animations/mostlycloudy.html
#       'clear-night': /community_plugin/lovelace-animated-background/background-animations/night.html
#       'fog': /community_plugin/lovelace-animated-background/background-animations/fog.html

# https://maykar.github.io/custom-header/
custom_header:
  hide_help: true
  compact_mode: false
  compact_header: false
  background: rgba(155, 155, 155, 0.25)
  # header_text: '{{ time }}<br/>{{ date }}'
#   button_text:
#     options: >-
#       {{ time }} - <ha-icon icon='mdi:weather-{{
#       states.weather.home.state }}'></ha-icon> {{
#       states.weather.home.attributes.temperature }}°
  chevrons: false
  exceptions:
    - conditions:
        user: kiosk
      config:
        kiosk_mode: true

views:
  # View tab title.
  - title: Home
    id: home
    icon: mdi:home-variant
    cards:
      - type: vertical-stack
        cards:
          # Weather Card
          - type: custom:weather-card
            entity: weather.home_2
          # Garbage
          - type: custom:garbage-collection-card
            entity: sensor.garbage
            icon_color: grey
            hide_date: true
            hide_before: 3
          # Recycling
          - type: custom:garbage-collection-card
            entity: sensor.recycling
            icon_color: green
            hide_date: true
            hide_before: 3
          # Car info
          - type: custom:vertical-stack-in-card
            title: Chargabug
            cards:
            - type: custom:bar-card
              title: Battery
              entity: sensor.chargabug_charge
              align: left
              title_position: inside
              icon: fas:car-battery
              padding: 25px
              show_icon: true
              severity:
                - value: 33
                  color: 'var(--label-badge-red)'
                - value: 66
                  color: 'var(--label-badge-yellow)'
                - value: 100
                  color: 'var(--label-badge-green)'
            - type: entities
              entities:    
                - type: custom:fold-entity-row
                  head: script.update_leaf
                  entities:
                    - binary_sensor.chargabug_plug_status
                    - binary_sensor.chargabug_charging_status
                    - switch.chargabug_climate_control
                    - sensor.chargabug_range
                    - sensor.chargabug_range_ac

      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - person.jesse
              - person.fred
          - type: entities
            entities:
              - person.floof
              - switch.floof_s_light
              - cover.floof_s_door
          # Rotom Card
          - type: custom:xiaomi-vacuum-card
            name: Rotom
            entity: vacuum.rotom
            image: /local/images/roomba.png
            vendor: roomba
            style: |
              ha-card .flex  {
                background: rgba(1, 1, 1, .5);
              }
              .grid-content {
                color: var(--primary-text-color);;
                text-shadow: none;
              }
              .grid-content div:nth-child(3) {
                display: none;
              }
              
  - title: Info
    id: info
    icon: mdi:android-messages
    cards:
      - type: custom:calendar-card
        title: "Calendar"
        progressBar: true
        entities:
          - calendar.jesse_calendar
          - calendar.fred_calendar
          - calendar.work_calendar
      - type: custom:auto-entities
        card:
          type: entities
          title: Tracking
          show_header_toggle: false
        show_empty: false
        filter:
          include:
            - entity_id: 'sensor.*track_package_*'
              options:
                secondary_info: last-changed

  - title: Living Room
    id: living-room
    icon: mdi:television
    cards:
      - type: vertical-stack
        cards:
        - type: media-control
          entity: media_player.playstation_4
        - type: horizontal-stack
          cards:
            - type: entity-button
              entity: media_player.playstation_4
              icon: far:playstation
              show_name: false
              tap_action:
                action: call-service
                service: ps4.send_command
                service_data:
                  entity_id: media_player.playstation_4
                  command: "ps"
            - type: entity-button
              entity: media_player.playstation_4
              icon: far:arrow-up
              show_name: false
              tap_action:
                action: call-service
                service: ps4.send_command
                service_data:
                  entity_id: media_player.playstation_4
                  command: "up"
            - type: entity-button
              entity: media_player.playstation_4
              icon: far:long-arrow-alt-right
              show_name: false
              tap_action:
                action: call-service
                service: ps4.send_command
                service_data:
                  entity_id: media_player.playstation_4
                  command: "option"
            - type: entity-button
              entity: media_player.playstation_4
              icon: far:long-arrow-alt-right
              show_name: false
              tap_action:
                action: call-service
                service: ps4.send_command
                service_data:
                  entity_id: media_player.playstation_4
                  command: "enter"
        - type: horizontal-stack
          cards:
            - type: entity-button
              entity: media_player.playstation_4
              icon: far:arrow-left
              show_name: false
              tap_action:
                action: call-service
                service: media_player.send_command
                service_data:
                  entity_id: ps4.playstation_4
                  command: "left"
            - type: entity-button
              entity: media_player.playstation_4
              icon: far:arrow-down
              show_name: false
              tap_action:
                action: call-service
                service: ps4.send_command
                service_data:
                  entity_id: media_player.playstation_4
                  command: "down"
            - type: entity-button
              entity: media_player.playstation_4
              icon: far:arrow-right
              show_name: false
              tap_action:
                action: call-service
                service: ps4.send_command
                service_data:
                  entity_id: media_player.playstation_4
                  command: "right"
            - type: entity-button
              entity: media_player.playstation_4
              icon: far:long-arrow-alt-left
              show_name: false
              tap_action:
                action: call-service
                service: ps4.send_command
                service_data:
                  entity_id: media_player.playstation_4
                  command: "back"
        - type: horizontal-stack
          cards:
            - type: entity-button
              entity: media_player.playstation_4
              icon: mdi:netflix
              #show_name: false
              name: "Netflix"
              tap_action:
                action: call-service
                service: media_player.select_source
                service_data:
                  entity_id: media_player.playstation_4
                  source: "Netflix"
                  
            - type: entity-button
              entity: media_player.playstation_4
              icon: mdi:brush
              name: "Crunchyroll"
              tap_action:
                action: call-service
                service: media_player.select_source
                service_data:
                  entity_id: media_player.playstation_4
                  source: "CRUNCHYROLL - WATCH THE LATEST ANIME and DRAMA"
                  
            - type: entity-button
              entity: media_player.playstation_4
              icon: far:fort-awesome
              name: "Disney+"
              tap_action:
                action: call-service
                service: media_player.select_source
                service_data:
                  entity_id: media_player.playstation_4
                  source: "Disney+"
                  
        - type: entity-button
          entity: switch.plant_light_2
          icon: mdi:fruit-pineapple
          icon_height: 50px
      - type: vertical-stack
        cards:
        - type: media-control
          entity: media_player.living_room_speaker
        - type: media-control
          entity: media_player.livingroom_chromecast

  - title: Lights
    icon: mdi:lightbulb-on-outline
    cards:
      - type: entities
        title: Kitchen
        entities:
          - switch.under_counter_lights_2
      - type: entities
        title: Living Room
        entities:
          - switch.plant_light_2
      - type: entities
        title: Hallway
        entities:
          - switch.hallway_light_2
      - type: entities
        title: Bedroom
        entities:
          - light.bedroom_light
      - type: entities
        title: Guest Bedroom
        entities:
          - switch.wemo_light_switch


  - title: Settings
    icon: mdi:settings
    path: settings
    cards:
      - type: custom:entity-attributes-card
        title: Backups
        heading_name: List
        heading_state: States
        filter:
          include:
            - key: sensor.snapshot_backup.last_snapshot
              name: 'Last snapshot'
            - key: sensor.snapshot_backup.snapshots_in_google_drive
              name: 'Snapshots in Google Drive'
            - key: sensor.snapshot_backup.snapshots_in_hassio
              name: 'Snapshots in Hassio'
      
      - type: custom:entity-attributes-card
        title: Backups
        heading_name: Car
        heading_state: States
        filter:
          include:
            - key: sensor.chargabug_charge.*

