#  _                   _                
# | |    _____   _____| | __ _  ___ ___ 
# | |   / _ \ \ / / _ \ |/ _` |/ __/ _ \
# | |__| (_) \ V /  __/ | (_| | (_|  __/
# |_____\___/ \_/ \___|_|\__,_|\___\___|

title: Maison Mauve
background: var(--background-image)
resources: !include lovelace/resources.yaml

# animated_background:
#   default_url: /community_plugin/lovelace-animated-background/background-animations/sunny.html
#   entity: "weather.dark_sky"
#   state_url:
#       'sunny': /community_plugin/lovelace-animated-background/background-animations/sunny.html
#       'partlycloudy': /community_plugin/lovelace-animated-background/background-animations/cloudy.html
#       'cloudy': /community_plugin/lovelace-animated-background/background-animations/cloudy.html
#       'mostlycloudy': /community_plugin/lovelace-animated-background/background-animations/mostlycloudy.html
#       'clear-night': /community_plugin/lovelace-animated-background/background-animations/night.html
#       'fog': /community_plugin/lovelace-animated-background/background-animations/fog.html

# https://maykar.github.io/custom-header/
custom_header:
  hide_help: true
  compact_mode: false
  compact_header: false
  background: rgba(155, 155, 155, 0.25)
  chevrons: false
  exceptions:
    - conditions:
        user: kiosk
      config:
        kiosk_mode: true

views:
  # View tab title.
  - title: Home
    id: home
    icon: mdi:home-variant
    cards: !include lovelace/views/home.yaml
              
  - title: Info
    id: info
    icon: mdi:android-messages
    cards: !include lovelace/views/info.yaml

  - title: People
    id: people
    icon: mdi:account-group
    cards: !include lovelace/views/people.yaml

  - title: Living Room
    id: living-room
    icon: mdi:television
    cards: !include lovelace/views/living_room.yaml

  - title: Lights
    icon: mdi:lightbulb-on-outline
    cards: !include lovelace/views/lights.yaml

  - title: System
    icon: mdi:settings
    path: system
    cards: !include lovelace/views/system.yaml

