#  _                   _                
# | |    _____   _____| | __ _  ___ ___ 
# | |   / _ \ \ / / _ \ |/ _` |/ __/ _ \
# | |__| (_) \ V /  __/ | (_| | (_|  __/
# |_____\___/ \_/ \___|_|\__,_|\___\___|

title: Maison Mauve
background: var(--background-image)
resources: !include lovelace/resources.yaml

# animated_background:
#   default_url: /community_plugin/lovelace-animated-background/background-animations/sunny.html
#   entity: "weather.dark_sky"
#   state_url:
#       'sunny': /community_plugin/lovelace-animated-background/background-animations/sunny.html
#       'partlycloudy': /community_plugin/lovelace-animated-background/background-animations/cloudy.html
#       'cloudy': /community_plugin/lovelace-animated-background/background-animations/cloudy.html
#       'mostlycloudy': /community_plugin/lovelace-animated-background/background-animations/mostlycloudy.html
#       'clear-night': /community_plugin/lovelace-animated-background/background-animations/night.html
#       'fog': /community_plugin/lovelace-animated-background/background-animations/fog.html

# https://maykar.github.io/custom-header/
custom_header:
  hide_help: true
  compact_mode: false
  compact_header: false
  background: rgba(155, 155, 155, 0.25)
  chevrons: false
  exceptions:
    - conditions:
        user: kiosk
      config:
        kiosk_mode: true

views:
  # View tab title.
  - title: Home
    id: home
    icon: mdi:home-variant
    cards:
      - type: vertical-stack
        cards:
          - type: custom:vertical-stack-in-card
            cards:
              # Weather Card
              - type: custom:weather-card
                entity: weather.environment_canada_home
              - type: custom:html-template-card
                ignore_line_breaks: true
                entities:
                  - sensor.warnings
                  - sensor.watches
                content: |
                  {{states.sensor.warnings }}

          
          - type: custom:home-feed-card
            show_empty: false
            show_notification_title: true
            
          # Garbage
          - type: custom:garbage-collection-card
            entity: sensor.garbage
            icon_color: grey
            hide_date: true
            hide_before: 3
            
          # Recycling
          - type: custom:garbage-collection-card
            entity: sensor.recycling
            icon_color: green
            hide_date: truef
            hide_before: 3
            
          - type: entities
            entities:
              - type: custom:multiple-entity-row
                name: Alarm
                entity: input_datetime.alarm_time
                show_state: false
                entities:
                  - input_datetime.alarm_time
                  - entity: input_boolean.alarmstatus
                    toggle: true
                  - entity: input_boolean.alarmweekday
                    toggle: true
                    
            
          - type: entities
            entities:
              - cover.bedroom_curtains
            
          # Car info
          - type: custom:vertical-stack-in-card
            icon: mdi:car-battery
            cards:
            - type: entities
              title: Chargabug
              show_header_toggle: false
              style: |
                .card-header {
                  padding-bottom: 6rem;
                  background: url(/local/images/leaf.png) no-repeat center 1rem;
                  background-size: contain;
                }
              entities:
                - type: custom:multiple-entity-row
                  name: Battery
                  entity: binary_sensor.chargabug_charging_status
                  show_state: false
                  icon: mdi:battery
                  entities:
                    - entity: sensor.chargabug_charge
                      name: false
                      unit: '%'
                    - entity: binary_sensor.chargabug_plug_status
                      icon: true
                    - entity: binary_sensor.chargabug_charging_status
                      icon: true
                - type: custom:multiple-entity-row
                  name: Range
                  entity: sensor.chargabug_range
                  show_state: false
                  entities:
                    - entity: sensor.chargabug_range_ac
                      name: With AC
                    - entity: sensor.chargabug_range
                      name: Without AC
                - type: custom:multiple-entity-row
                  name: Updated
                  entity: sensor.leaf_last_update
                  show_state: false
                  icon: mdi:calendar
                  entities:
                    - entity: sensor.leaf_last_update
                      name: Last Uptated
                    - entity: sensor.leaf_last_attempt
                      name: Last Attempt
                - type: custom:multiple-entity-row
                  name: Updating
                  entity: sensor.leaf_updating
                  show_state: false
                  icon: mdi:calendar
                  entities:
                    - name: Update Now
                      icon: mdi:refresh
                      tap_action:
                        action: call-service
                        service: nissan_leaf.update
                        service_data: 
                          vin: !secret leaf_vin
                    - entity: sensor.leaf_updating
                      name: Updating
                    - entity: sensor.leaf_next_update
                      name: Next Attempt

      - type: vertical-stack
        cards:
          - type: entities
            title: Rotom
            show_header_toggle: false
            style: |
              .card-header {
                padding-bottom: 6rem;
                background: url(/local/images/roomba.png) no-repeat center center;
                background-size: contain;
              }
            entities:
            - type: custom:multiple-entity-row
              entity: sensor.rest980
              show_state: false
              name: Battery
              entities:
                - attribute: batPct
                  name: Battery
                  unit: '%'
                - icon: mdi:play
                  action:
                    script: script.1582319163683
            - type: custom:multiple-entity-row
              entity: sensor.rest980
              name: Info
              show_state: false
              entities:
                - sensor.vacuum_phase
                - sensor.vacuum_cycle
            conditions:
              - entity: sensor.vacuum_dock
                state_not: 'Ready'
            card:
              - type: picture-glance
                aspect_ratio: 0%
                camera_image: camera.roomba
                entities: []
              
  - title: Info
    id: info
    icon: mdi:android-messages
    cards:
      - type: custom:calendar-card
        title: "Calendar"
        progressBar: true
        entities:
          - calendar.jesse_calendar
          - calendar.fred_calendar
          - calendar.work_calendar
          
      - type: custom:auto-entities
        card:
          type: entities
          title: Tracking
          show_header_toggle: false
        show_empty: false
        filter:
          include:
            - entity_id: 'sensor.*track_package_*'
              options:
                secondary_info: last-changed
                
      - type: custom:vertical-stack-in-card
        title: Bob
        cards:
          - type: custom:miflora-card
            image: images/pineapple.jpg
            min_moisture: 15
            max_moisture: 60
            min_conductivity: 350
            min_temperature: 12
            entities:
              - moisture:sensor.pineapple_sensor_moisture
              - intensity:sensor.pineapple_sensor_light_intensity
              - temperature:sensor.pineapple_sensor_temperature
              - conductivity:sensor.pineapple_sensor_conductivity
              - battery:sensor.pineapple_sensor_battery
          - type: entity-button
            entity: switch.plant_light
            icon: mdi:fruit-pineapple
            icon_height: 50px

  - title: People
    id: people
    icon: mdi:account-group
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - sensor.jesse_geocode
              - sensor.pixel_3_battery_level
              - sensor.pixel_3_wifi_connection
          - type: entities
            title: "Jesse's Google Fit"
            show_header_toggle: false
            entities:
              - sensor.jesse_s_google_fit_steps
              - sensor.jesse_s_google_fit_weight
              - sensor.jesse_s_google_fit_distance
              - sensor.jesse_s_google_fit_move_time
              - sensor.jesse_s_google_fit_calories
      
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - sensor.fred_geocode
              - sensor.pixel_2_battery_level
              - sensor.pixel_2_wifi_connection
      
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - person.floof
              - switch.floof_s_light
              - cover.floof_s_door
          - type: picture-glance
            title: Floof Cam
            entities: []
            camera_image: camera.floof_cam

  - title: Living Room
    id: living-room
    icon: mdi:television
    cards:
      - type: media-control
        entity: media_player.playstation_4
      - type: entities
        entities:
          - type: "custom:button-entity-row"
            buttons:
              - - icon: fab:playstation
                  service: ps4.send_command
                  service_data:
                    entity_id: media_player.playstation_4
                    command: "ps"
                - icon: fas:arrow-up
                  service: ps4.send_command
                  service_data:
                    entity_id: media_player.playstation_4
                    command: "up"
                - icon: fas:long-arrow-alt-right
                  service: ps4.send_command
                  service_data:
                    entity_id: media_player.playstation_4
                    command: "option"
                - icon: fas:long-arrow-alt-right
                  service: ps4.send_command
                  service_data:
                    entity_id: media_player.playstation_4
                    command: "enter"
              - - icon: fas:arrow-left
                  service: ps4.send_command
                  service_data:
                    entity_id: media_player.playstation_4
                    command: "left"
                - icon: fas:arrow-down
                  service: ps4.send_command
                  service_data:
                    entity_id: media_player.playstation_4
                    command: "down"
                - icon: fas:arrow-right
                  service: ps4.send_command
                  service_data:
                    entity_id: media_player.playstation_4
                    command: "right"
                - icon: fas:long-arrow-alt-left
                  service: ps4.send_command
                  service_data:
                    entity_id: media_player.playstation_4
                    command: "back"

          - type: "custom:button-entity-row"
            buttons:
              - icon: mdi:netflix
                name: "Netflix"
                service: media_player.select_source
                service_data:
                  entity_id: media_player.playstation_4
                  source: "Netflix"
              - icon: mdi:brush
                name: "Crunchyroll"
                service: media_player.select_source
                service_data:
                  entity_id: media_player.playstation_4
                  source: "CRUNCHYROLL - WATCH THE LATEST ANIME and DRAMA"
              - icon: fab:fort-awesome
                name: "Disney+"
                service: media_player.select_source
                service_data:
                  entity_id: media_player.playstation_4
                  source: "Disney+"

      - type: vertical-stack
        cards:
        - type: media-control
          entity: media_player.living_room_speaker
        - type: media-control
          entity: media_player.livingroom_chromecast

  - title: Lights
    icon: mdi:lightbulb-on-outline
    cards:
      - type: entities
        title: Lights
        state_color: true
        show_header_toggle: false
        entities:
          - entity: switch.under_counter_lights
            name: Kitchen counter lights
          - entity: switch.plant_light
            name: Pineapple (Bob)
          - entity: switch.hallway_light
            name: Hallway
          - entity: light.bedroom_light
            name: Bedroom light
          - entity: switch.wemo_light_switch
            name: Guest Bedroom
          - type: custom:multiple-entity-row
            name: Outdoor
            toggle: true
            state_header: Both
            entity: switch.smart_outdoor_plug
            entities:
              - entity: switch.switch_1
                toggle: true
                name: 'Front'
              - entity: switch.switch_2
                toggle: true
                name: 'Back'

  - title: Settings
    icon: mdi:settings
    path: settings
    cards:
      - type: entities
        entities:
        - type: custom:gui-sandbox
      - type: custom:entity-attributes-card
        title: Backups
        heading_name: List
        heading_state: States
        filter:
          include:
            - key: sensor.snapshot_backup.last_snapshot
              name: 'Last snapshot'
            - key: sensor.snapshot_backup.snapshots_in_google_drive
              name: 'Snapshots in Google Drive'
            - key: sensor.snapshot_backup.snapshots_in_hassio
              name: 'Snapshots in Hassio'

