#   ____                           _ 
#  / ___| ___ _ __   ___ _ __ __ _| |
# | |  _ / _ \ '_ \ / _ \ '__/ _` | |
# | |_| |  __/ | | |  __/ | | (_| | |
#  \____|\___|_| |_|\___|_|  \__,_|_|


- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: seventeentrack
  username: !secret email
  password: !secret old_password

- platform: uptime
- platform: season
- platform: version
  source: hassio
  image: raspberrypi2
