#  ____                   _        _____ _ _   
# / ___| ___   ___   __ _| | ___  |  ___(_) |_ 
# | |  _ / _ \ / _ \ / _` | |/ _ \ | |_  | | __|
# | |_| | (_) | (_) | (_| | |  __/ |  _| | | |_ 
# \____|\___/ \___/ \__, |_|\___| |_|   |_|\__|
#                    |___/ 

- platform: google_fit
  name: "Jesse's Google Fit"
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret