#  _   _      _                      _    
# | \ | | ___| |___      _____  _ __| | __
# |  \| |/ _ \ __\ \ /\ / / _ \| '__| |/ /
# | |\  |  __/ |_ \ V  V / (_) | |  |   < 
# |_| \_|\___|\__| \_/\_/ \___/|_|  |_|\_\

- platform: google_wifi
  name: Google WiFi
  host: 192.168.2.13
